- name: "system: make dirs"
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ USER_DIRECTORIES }}"

- include: apt.yml

################################################################################
# miscellaneous
################################################################################

- name: "pip: setup symlink"
  become: yes
  file:
    src: /usr/bin/pip3
    dest: /usr/bin/pip
    state: link

- name: download rustup
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.rs
    mode: 0755
  tags: ['rust']

- name: install rustup
  shell: sh /tmp/rustup.rs -y
  tags: ['rust']

#- name: "stow: setup dotfiles"
#  command: stow -t ~ .
#  args:
#    chdir: ~/src/linux_configs/dotfiles

- name: "zsh: configure zplug"
  git:
    repo: https://github.com/zplug/zplug
    dest: ~/.zplug

- name: "zsh: configure fzf"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: "zsh: configure fzf"
  git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf
    depth: 1

- name: "fzf: configure plugin"
  command: ~/.fzf/install --no-bash --no-fish --all --completion --key-bindings

- name: "gem: install for system"
  become: yes
  gem:
    name: "{{ item }}"
    user_install: no
    include_doc: yes
    state: latest
  with_items:
    - neovim
    - json
    - terraform
    - lolcat
    - tmuxinator

################################################################################
# additional docker configurations
################################################################################

- name: "docker: mark docker"
  become: yes
  command: apt-mark hold docker-ce
  tags: ['docker']

- name: "docker: add my user to docker group"
  become: yes
  user:
    append: yes
    user: "{{ ansible_user_id }}"
    groups: docker

################################################################################
# plantuml
################################################################################

- name: "plantuml: download plantuml.jar"
  get_url:
    url: http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
    dest: ~/java/plantuml.jar

- name: "plantuml: copy plantuml binary"
  copy:
    src: plantuml
    dest: ~/bin/plantuml
    mode: 0755

################################################################################
# slack
################################################################################

- name: "slack: download"
  get_url:
    url: https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb
    dest: /tmp/slack-desktop.deb
  tags: ['slack']

- name: "slack: install"
  become: yes
  apt:
    deb: /tmp/slack-desktop.deb
  tags: ['slack']

################################################################################
# configure tmux
################################################################################

- name: copy tmuxinator templates
  copy:
    src: "{{ item }}"
    dest: ~/.config/tmuxinator/{{ TMUXINATOR_FILES}}
  with_items: "{{ TMUXINATOR_FILES }}"
  tags: tmux


#- include: env_managers.yml

- include: autocompleters.yml
