- name: "APT: upgrade system packages"
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
  tags: ['apt']

- include: apt_repositories.yml

- name: "APT: Install packages"
  become: yes
  apt:
    name: "{{ APT_PROGRAMS }}"
    update_cache: yes
  tags: ['apt']
