[tools]
terraform = "1.7.5"
terraform-ls = "latest"
tmux = "3.4"
awscli = "2.15.52"
go = "1.19.3"
node = "20.0.0"
yarn = "1.22.11"
python = "3.12.3"
zoxide = "latest"
github-cli = "latest"
k9s = "latest"
neovim = "0.10.0"
poetry = "latest"
kubectl = "1.28.0"
azure-cli = "2.50.0"
tflint = "latest"
