[tools]
"cargo:fd-find" = "latest"
"cargo:ripgrep" = "latest"
"cargo:tree-sitter-cli" = "latest"
awscli = "2.15.52"
azure-cli = "2.50.0"
github-cli = "latest"
go = "1.19.3"
granted = "latest"
kubectl = "1.28.0"
lsd = "1.1.2"
neovim = "0.10.0"
poetry = "latest"
ruby = "3.3.4"
rust = "1.79.0"
terraform = "1.7.5"
terraform-ls = "latest"
tflint = "latest"
tmux = "3.5a"
vault = "1.17.2+ent"
yarn = "4.3.1"
zoxide = "latest"
kubecolor = "latest"
terragrunt = "latest"
helm = "latest"
gcloud = "latest"
node = "22.10.0"
python = "3.12.5"
k9s = "latest"
delta = "latest"
argocd = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["terraform"]

[alias.node.versions]
latest = '20'
