[tools]
terraform = "1.7.5"
terraform-ls = "latest"
tmux = "latest"
awscli = "2.15.52"
go = "1.19.3"
node = "20.0.0"
yarn = "latest"
python = "3.12.3"
zoxide = "latest"
github-cli = "latest"
k9s = "latest"
neovim = "0.10.0"
poetry = "latest"
kubectl = "1.28.0"
azure-cli = "2.50.0"
tflint = "latest"
lsd = "1.1.2"
rust = "latest"
"cargo:ripgrep" = "latest"
"cargo:fd-find" = "latest"
ruby = "latest"
"cargo:tree-sitter-cli" = "latest"
vault = "latest"
granted = "latest"

[settings]
experimental = true

[alias.node]
latest = '20'
