name: Add Github username as comment

on:
  pull_request: {branches: master}

jobs:
  github_username_commentor:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
      env:
        GITHUB_TOKEN: '${{ secrets.GTHUB_TOKEN }}'
      - run: 'echo ${{ GITHUB_ACTOR }}'
